# Generated by Django 6.1.1 on 2026-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0002_contactrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Вставте пряме публічне посилання на файл зображення. Посилання на сторінку альбому Google Photos не є прямим посиланням на фото.",
                        max_length=2048,
                        verbose_name="Посилання на фото",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Опис фото для доступності",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Менше число — раніше відображення.",
                        verbose_name="Порядок показу",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
            ],
            options={
                "verbose_name": "Слайд головної",
                "verbose_name_plural": "Слайди головної",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Orders",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
