# Generated by Django 6.1.1 on 2026-10-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0003_heroslide_alter_contactrequest_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heroslide",
            options={
                "ordering": ["order", "pk"],
                "verbose_name": "Main slides",
                "verbose_name_plural": "Main slides",
            },
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="alt_text",
        ),
    ]
