# Generated by Django 6.1.1 on 2026-10-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0004_alter_heroslide_options_remove_heroslide_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="image_url",
            field=models.URLField(
                help_text="Вставте пряме публічне посилання на фото або посилання на файл Google Drive (наприклад, drive.google.com/file/d/ID/view). Доступ до файлу має бути відкритий для всіх за посиланням. Посилання на альбоми Google Photos не підтримуються.",
                max_length=2048,
                verbose_name="Посилання на фото",
            ),
        ),
    ]
