# Generated by Django 6.1.1 on 2026-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0005_alter_heroslide_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Назва фотосесії"),
                ),
                (
                    "cover_url",
                    models.URLField(
                        help_text="Підтримується пряме посилання або посилання Google Drive на файл.",
                        max_length=2048,
                        verbose_name="Посилання на обкладинку",
                    ),
                ),
                (
                    "drive_folder_url",
                    models.URLField(
                        help_text="Папка має бути доступна всім, хто має посилання.",
                        max_length=2048,
                        verbose_name="Посилання на папку Google Drive",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Менше число — раніше відображення.",
                        verbose_name="Порядок показу",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Фотосесія",
                "verbose_name_plural": "Фотосесії",
                "ordering": ["order", "pk"],
            },
        ),
    ]
