# Generated by Django 6.1.1 on 2026-10-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0006_photosession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photosession",
            options={
                "ordering": ["order", "pk"],
                "verbose_name": "New Photoshoots",
                "verbose_name_plural": "New Photoshoots",
            },
        ),
    ]
