# Generated by Django 6.1.1 on 2026-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0007_alter_photosession_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Biography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="ПРО МЕНЕ", max_length=255, verbose_name="Заголовок"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Розділяйте абзаци порожнім рядком.",
                        verbose_name="Текст біографії",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Якщо фото не завантажено, використовується стандартне зображення Biographical.jpg.",
                        upload_to="biography/",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biography",
                "verbose_name_plural": "Biography",
                "ordering": ["pk"],
            },
        ),
    ]
