# Generated by Django 6.1.1 on 2026-10-04 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_photo_session_types(apps, schema_editor):
    photo_session_type = apps.get_model("yarosh_website", "PhotoSessionType")
    photo_session_type.objects.using(schema_editor.connection.alias).bulk_create(
        [
            photo_session_type(name="Портрети", order=1),
            photo_session_type(name="Тематичні фотосесії", order=2),
            photo_session_type(name="Заходи", order=3),
            photo_session_type(name="Корпоративні фотосесії", order=4),
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0009_seed_biography"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoSessionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Тип фотосесії"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок показу"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип фотосесії",
                "verbose_name_plural": "Типи фотосесій",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Ідентифікатор",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Перший візит"
                    ),
                ),
            ],
            options={
                "verbose_name": "Унікальний відвідувач",
                "verbose_name_plural": "Унікальні відвідувачі",
                "ordering": ["-first_seen"],
            },
        ),
        migrations.CreateModel(
            name="PhotoSessionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=2000, verbose_name="Коментар")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "photo_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="yarosh_website.photosession",
                        verbose_name="Фотосесія",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_session_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коментар до фотосесії",
                "verbose_name_plural": "Коментарі до фотосесій",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoSessionLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "photo_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like_records",
                        to="yarosh_website.photosession",
                        verbose_name="Фотосесія",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_session_like_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вподобання фотосесії",
                "verbose_name_plural": "Вподобання фотосесій",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="photosession",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_photo_sessions",
                through="yarosh_website.PhotoSessionLike",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Вподобання",
            ),
        ),
        migrations.AddField(
            model_name="photosession",
            name="photo_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo_sessions",
                to="yarosh_website.photosessiontype",
                verbose_name="Тип фотосесії",
            ),
        ),
        migrations.CreateModel(
            name="PhotoSessionShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "photo_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="yarosh_website.photosession",
                        verbose_name="Фотосесія",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_session_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_session_shares",
                        to="yarosh_website.sitevisitor",
                        verbose_name="Пристрій",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поширення фотосесії",
                "verbose_name_plural": "Поширення фотосесій",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="photosessionlike",
            constraint=models.UniqueConstraint(
                fields=("photo_session", "user"), name="unique_photo_session_like"
            ),
        ),
        migrations.RunPython(
            create_default_photo_session_types,
            migrations.RunPython.noop,
        ),
    ]
