# Generated by Django 6.1.1 on 2026-10-04 15:25

from django.db import migrations, models


def populate_search_fields(apps, schema_editor):
    alias = schema_editor.connection.alias
    photo_session = apps.get_model("yarosh_website", "PhotoSession")
    photo_type = apps.get_model("yarosh_website", "PhotoSessionType")

    sessions = list(
        photo_session.objects.using(alias).only("pk", "title").iterator()
    )
    for session in sessions:
        session.search_title = session.title.casefold()
    photo_session.objects.using(alias).bulk_update(
        sessions,
        ["search_title"],
        batch_size=500,
    )

    types = list(photo_type.objects.using(alias).only("pk", "name").iterator())
    for item in types:
        item.search_name = item.name.casefold()
    photo_type.objects.using(alias).bulk_update(
        types,
        ["search_name"],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "yarosh_website",
            "0010_photosessiontype_sitevisitor_photosessioncomment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="photosession",
            name="search_title",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="photosessiontype",
            name="search_name",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=100
            ),
        ),
        migrations.RunPython(
            populate_search_fields,
            migrations.RunPython.noop,
        ),
    ]
