# Generated by Django 6.1.1 on 2026-10-04 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0011_photosession_search_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photosession",
            options={
                "ordering": ["-created_at", "-pk"],
                "verbose_name": "New Photoshoots",
                "verbose_name_plural": "New Photoshoots",
            },
        ),
        migrations.AddField(
            model_name="photosession",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Дата публікації",
            ),
        ),
    ]
