# Generated by Django 6.1.1 on 2026-10-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0012_alter_photosession_options_photosession_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photosession",
            name="photo_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo_sessions",
                to="yarosh_website.photosessiontype",
                verbose_name="Тип фотосесії",
            ),
        ),
    ]
