# Generated by Django 6.1.1 on 2026-10-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0013_alter_photosession_photo_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photosessioncomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Photo session comment",
                "verbose_name_plural": "Photo session comments",
            },
        ),
        migrations.AlterModelOptions(
            name="photosessionlike",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Photo session like",
                "verbose_name_plural": "Photo session likes",
            },
        ),
        migrations.AlterModelOptions(
            name="photosessionshare",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Photo session share",
                "verbose_name_plural": "Photo session shares",
            },
        ),
        migrations.AlterModelOptions(
            name="photosessiontype",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Photo session type",
                "verbose_name_plural": "Photo session types",
            },
        ),
    ]
