# Generated by Django 6.1.1 on 2026-10-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yarosh_website", "0014_alter_photosessioncomment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photosessioncomment",
            options={
                "ordering": ["created_at", "pk"],
                "verbose_name": "Photo session comment",
                "verbose_name_plural": "Photo session comments",
            },
        ),
        migrations.AddField(
            model_name="photosessioncomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="yarosh_website.photosessioncomment",
                verbose_name="Батьківський коментар",
            ),
        ),
    ]
